apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/load-balancer-name: dwx-dev-druid-alb-ingress
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/subnets: <<-->>
    alb.ingress.kubernetes.io/target-type: ip
  name: dwx-dev-druid-alb-ingress
  namespace: druid-raw
spec:
  ingressClassName: alb
  rules:
  - http:
      paths:
      - backend:
          service:
            name: druid-raw-routers
            port:
              number: 8888
        path: /
        pathType: Prefix

